In [2]:
import pandas as pd
from pathlib import Path

# Caminho direto para a partição BTCUSDT (L2)
path = Path(
    "/Users/edmundobrown/Documents/MLGeral/AI-Finance/teste-cursor/crypto-mkt-state/data/03_primary/crypto/ohlcv_daily/ADAUSDT")
   

# Ler parquet
df = pd.read_parquet(path)

# Visão geral
print("Shape:", df.shape)
print("\nIndex:")
print(type(df.index))
print(df.index.tz)

print("\nDtypes:")
print(df.dtypes)

print("\nHead:")
display(df.head())

print("\nTail:")
display(df.tail())

Shape: (2208, 56)

Index:
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>
UTC

Dtypes:
open                                   float64
high                                   float64
low                                    float64
close                                  float64
volume                                 float64
close_time                 datetime64[ns, UTC]
quote_volume                           float64
trades                                   int64
taker_buy_base_volume                  float64
taker_buy_quote_volume                 float64
asset                                   object
symbol                                  object
source                                  object
ingestion_ts               datetime64[us, UTC]
interval                                object
log_return_1d                          float64
log_return_7d                          float64
log_return_21d                         float64
log_return_63d                         float64
volatility_7d                          float64
volatility_21d                         float64
volatility_63d                         float64
price_range_7d                         float64
price_range_21d                        float64
realized_volatility_7d                 float64
realized_volatility_21d                float64
volume_ma_7d                           float64
volume_ma_21d                          float64
volume_zscore_7d                       float64
volume_zscore_21d                      float64
volume_change_7d                       float64
quote_volume_ma_7d                     float64
quote_volume_ma_21d                    float64
trades_ma_7d                           float64
trades_ma_21d                          float64
trades_zscore_7d                       float64
buy_pressure_7d                        float64
buy_pressure_21d                       float64
price_ma_7d                            float64
price_ma_21d                           float64
price_ma_63d                           float64
price_slope_21d                        float64
price_slope_63d                        float64
price_position_7d                      float64
price_position_21d                     float64
candle_body_ratio                      float64
candle_body_ratio_7d                   float64
candle_body_ratio_21d                  float64
upper_shadow_ratio                     float64
lower_shadow_ratio                     float64
shadow_ratio_7d                        float64
shadow_ratio_21d                       float64
high_low_ratio_7d                      float64
high_low_ratio_21d                     float64
autocorr_return_1d                     float64
hurst_exponent_63d                     float64
dtype: object

Head:

,open,high,low,close,volume,close_time,quote_volume,trades,taker_buy_base_volume,taker_buy_quote_volume,...,candle_body_ratio_7d,candle_body_ratio_21d,upper_shadow_ratio,lower_shadow_ratio,shadow_ratio_7d,shadow_ratio_21d,high_low_ratio_7d,high_low_ratio_21d,autocorr_return_1d,hurst_exponent_63d
timestamp,,,,,,,,,,,,,,,,,,,,,
2020-01-01 00:00:00+00:00,0.03285,0.03380,0.03270,0.03348,29827408.5,2020-01-01 23:59:59.999000+00:00,9.955444e+05,6116,14857010.7,4.958391e+05,...,NaN,NaN,0.290909,0.136364,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-02 00:00:00+00:00,0.03345,0.03348,0.03218,0.03269,42826456.1,2020-01-02 23:59:59.999000+00:00,1.406391e+06,7453,19344719.1,6.353559e+05,...,NaN,NaN,0.023077,0.392308,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-03 00:00:00+00:00,0.03269,0.03446,0.03236,0.03417,102581046.7,2020-01-03 23:59:59.999000+00:00,3.470143e+06,15068,53816813.9,1.820772e+06,...,NaN,NaN,0.138095,0.157143,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-04 00:00:00+00:00,0.03417,0.03450,0.03375,0.03434,55528746.4,2020-01-04 23:59:59.999000+00:00,1.892276e+06,7992,26567804.8,9.061852e+05,...,NaN,NaN,0.213333,0.560000,NaN,NaN,NaN,NaN,NaN,NaN
2020-01-05 00:00:00+00:00,0.03436,0.03527,0.03419,0.03460,71815282.1,2020-01-05 23:59:59.999000+00:00,2.493890e+06,10424,33390473.2,1.159713e+06,...,NaN,NaN,0.620370,0.157407,NaN,NaN,NaN,NaN,NaN,NaN

Tail:

,open,high,low,close,volume,close_time,quote_volume,trades,taker_buy_base_volume,taker_buy_quote_volume,...,candle_body_ratio_7d,candle_body_ratio_21d,upper_shadow_ratio,lower_shadow_ratio,shadow_ratio_7d,shadow_ratio_21d,high_low_ratio_7d,high_low_ratio_21d,autocorr_return_1d,hurst_exponent_63d
timestamp,,,,,,,,,,,,,,,,,,,,,
2026-01-12 00:00:00+00:00,0.3910,0.4036,0.3815,0.3862,130152762.6,2026-01-12 23:59:59.999000+00:00,5.094300e+07,233795,63661248.4,2.491346e+07,...,0.294003,0.462193,0.570136,0.212670,0.705997,0.537807,1.146527,1.327869,0.174164,0.513688
2026-01-13 00:00:00+00:00,0.3862,0.4267,0.3850,0.4218,161630853.6,2026-01-13 23:59:59.999000+00:00,6.577354e+07,265931,79977926.3,3.250250e+07,...,0.409272,0.482013,0.117506,0.028777,0.590728,0.517987,1.118480,1.327869,0.104782,0.473414
2026-01-14 00:00:00+00:00,0.4219,0.4273,0.4097,0.4143,148337662.9,2026-01-14 23:59:59.999000+00:00,6.224105e+07,248749,74244458.8,3.115511e+07,...,0.373455,0.479320,0.306818,0.261364,0.626545,0.520680,1.120052,1.327869,0.006298,0.473020
2026-01-15 00:00:00+00:00,0.4144,0.4144,0.3891,0.3936,137830356.8,2026-01-15 23:59:59.999000+00:00,5.531193e+07,213118,69557983.3,2.791714e+07,...,0.443046,0.490027,0.000000,0.177866,0.556954,0.509973,1.120052,1.327869,0.061802,0.478454
2026-01-16 00:00:00+00:00,0.3937,0.3945,0.3788,0.3870,78559344.2,2026-01-16 23:59:59.999000+00:00,3.045337e+07,118964,36289445.7,1.406779e+07,...,0.469500,0.492563,0.050955,0.522293,0.530500,0.507437,1.128036,1.327869,0.079529,0.467016